/**
 * Mapping of manufacturer names to their numeric IDs
 * Based on the Garmin FIT SDK Profile
 */
export interface Manufacturer {
    id: number;
    name: string;
}

export const MANUFACTURERS: Manufacturer[] = [
    { id: 1, name: "Garmin" },
    { id: 2, name: "Garmin FR405 ANTFS" },
    { id: 3, name: "Zephyr" },
    { id: 4, name: "Dayton" },
    { id: 5, name: "IDT" },
    { id: 6, name: "SRM" },
    { id: 7, name: "Quarq" },
    { id: 8, name: "iBike" },
    { id: 9, name: "Saris" },
    { id: 10, name: "Spark HK" },
    { id: 11, name: "Tanita" },
    { id: 12, name: "Echowell" },
    { id: 13, name: "Dynastream OEM" },
    { id: 14, name: "Nautilus" },
    { id: 15, name: "Dynastream" },
    { id: 16, name: "Timex" },
    { id: 17, name: "Metrigear" },
    { id: 18, name: "Xelic" },
    { id: 19, name: "Beurer" },
    { id: 20, name: "Cardiosport" },
    { id: 21, name: "A&D" },
    { id: 22, name: "HMM" },
    { id: 23, name: "Suunto" },
    { id: 24, name: "Thita Elektronik" },
    { id: 25, name: "GPulse" },
    { id: 26, name: "Clean Mobile" },
    { id: 27, name: "Pedal Brain" },
    { id: 28, name: "Peaksware" },
    { id: 29, name: "Saxonar" },
    { id: 30, name: "Lemond Fitness" },
    { id: 31, name: "Dexcom" },
    { id: 32, name: "Wahoo Fitness" },
    { id: 33, name: "Octane Fitness" },
    { id: 34, name: "Archinoetics" },
    { id: 35, name: "The Hurt Box" },
    { id: 36, name: "Citizen Systems" },
    { id: 37, name: "Magellan" },
    { id: 38, name: "Osynce" },
    { id: 39, name: "Holux" },
    { id: 40, name: "Concept2" },
    { id: 42, name: "One Giant Leap" },
    { id: 43, name: "Ace Sensor" },
    { id: 44, name: "Brim Brothers" },
    { id: 45, name: "Xplova" },
    { id: 46, name: "Perception Digital" },
    { id: 47, name: "BF1 Systems" },
    { id: 48, name: "Pioneer" },
    { id: 49, name: "Spantec" },
    { id: 50, name: "Metalogics" },
    { id: 51, name: "4iiiis" },
    { id: 52, name: "Seiko Epson" },
    { id: 53, name: "Seiko Epson OEM" },
    { id: 54, name: "ifor Powell" },
    { id: 55, name: "Maxwell Guider" },
    { id: 56, name: "Star Trac" },
    { id: 57, name: "Breakaway" },
    { id: 58, name: "Alatech Technology" },
    { id: 59, name: "MIO Technology Europe" },
    { id: 60, name: "Rotor" },
    { id: 61, name: "Geonaute" },
    { id: 62, name: "ID Bike" },
    { id: 63, name: "Specialized" },
    { id: 64, name: "Wtek" },
    { id: 65, name: "Physical Enterprises" },
    { id: 66, name: "North Pole Engineering" },
    { id: 67, name: "Bkool" },
    { id: 68, name: "Cateye" },
    { id: 69, name: "Stages Cycling" },
    { id: 70, name: "Sigmasport" },
    { id: 71, name: "Tomtom" },
    { id: 72, name: "Peripedal" },
    { id: 73, name: "Wattbike" },
    { id: 76, name: "Moxy" },
    { id: 77, name: "Ciclosport" },
    { id: 78, name: "Powerbahn Hub" },
    { id: 79, name: "Acorn Projects APS" },
    { id: 80, name: "Lifebeam" },
    { id: 81, name: "Bontrager" },
    { id: 82, name: "Wellgo" },
    { id: 83, name: "Scosche" },
    { id: 84, name: "Magura" },
    { id: 85, name: "Woodway" },
    { id: 86, name: "Elite" },
    { id: 87, name: "Nielsen Kellerman" },
    { id: 88, name: "DK City" },
    { id: 89, name: "Tacx" },
    { id: 90, name: "Direction Technology" },
    { id: 91, name: "Magtonic" },
    { id: 92, name: "1Partcarbon" },
    { id: 93, name: "Inside Ride Technologies" },
    { id: 94, name: "Sound Of Motion" },
    { id: 95, name: "Stryd" },
    { id: 96, name: "Icg" },
    { id: 97, name: "MiPulse" },
    { id: 98, name: "BSX Athletics" },
    { id: 99, name: "Look" },
    { id: 100, name: "Campagnolo SRL" },
    { id: 101, name: "Body Bike Smart" },
    { id: 102, name: "Praxisworks" },
    { id: 103, name: "Limits Technology" },
    { id: 104, name: "Topaction Technology" },
    { id: 105, name: "Cosinuss" },
    { id: 106, name: "Fitcare" },
    { id: 107, name: "Magene" },
    { id: 108, name: "Giant Manufacturing Co" },
    { id: 109, name: "Tigrasport" },
    { id: 110, name: "Salutron" },
    { id: 111, name: "Technogym" },
    { id: 112, name: "Bryton Sensors" },
    { id: 113, name: "Latitude Limited" },
    { id: 114, name: "Soaring Technology" },
    { id: 115, name: "Igpsport" },
    { id: 116, name: "Thinkrider" },
    { id: 117, name: "Gopher Sport" },
    { id: 118, name: "Waterrower" },
    { id: 119, name: "Orangetheory" },
    { id: 120, name: "Inpeak" },
    { id: 121, name: "Kinetic" },
    { id: 122, name: "Johnson Health Tech" },
    { id: 123, name: "Polar Electro" },
    { id: 124, name: "Seesense" },
    { id: 125, name: "NCI Technology" },
    { id: 126, name: "Iqsquare" },
    { id: 127, name: "Leomo" },
    { id: 128, name: "Ifit Com" },
    { id: 129, name: "Coros Byte" },
    { id: 255, name: "Development" },
    { id: 257, name: "Healthandlife" },
    { id: 258, name: "Lezyne" },
    { id: 259, name: "Scribe Labs" },
    { id: 260, name: "Zwift" },
    { id: 261, name: "Watteam" },
    { id: 262, name: "Recon" },
    { id: 263, name: "Favero Electronics" },
    { id: 264, name: "Dynovelo" },
    { id: 265, name: "Strava" },
    { id: 266, name: "Precor" },
    { id: 267, name: "Bryton" },
    { id: 268, name: "Sram" },
    { id: 269, name: "Navman" },
    { id: 270, name: "Cobi" },
    { id: 271, name: "Spivi" },
    { id: 272, name: "Mio Magellan" },
    { id: 273, name: "Evesports" },
    { id: 274, name: "Sensitivus Gauge" },
    { id: 275, name: "Podoon" },
    { id: 276, name: "Life Time Fitness" },
    { id: 277, name: "Falco E Motors" },
    { id: 278, name: "Minoura" },
    { id: 279, name: "Cycliq" },
    { id: 280, name: "Luxottica" },
    { id: 281, name: "Trainer Road" },
    { id: 282, name: "The Sufferfest" },
    { id: 283, name: "Fullspeedahead" },
    { id: 284, name: "Virtualtraining" },
    { id: 285, name: "Feedbacksports" },
    { id: 286, name: "Omata" },
    { id: 287, name: "Vdo" },
    { id: 288, name: "Magneticdays" },
    { id: 289, name: "Hammerhead" },
    { id: 290, name: "Kinetic By Kurt" },
    { id: 291, name: "Shapelog" },
    { id: 292, name: "Dabuziduo" },
    { id: 293, name: "Jetblack" },
    { id: 294, name: "Coros" },
    { id: 295, name: "Virtugo" },
    { id: 296, name: "Velosense" },
    { id: 297, name: "Cycligentinc" },
    { id: 298, name: "Trailforks" },
    { id: 299, name: "Mahle Ebikemotion" },
    { id: 300, name: "Nurvv" },
    { id: 301, name: "Microprogram" },
    { id: 302, name: "Zone Five Software" },
    { id: 303, name: "Greenteg" },
    { id: 304, name: "Yamaha Motors" },
    { id: 305, name: "Whoop" },
    { id: 306, name: "Gravaa" },
    { id: 307, name: "Onelap" },
    { id: 308, name: "Monark Exercise" },
    { id: 309, name: "Form" },
    { id: 310, name: "Decathlon" },
    { id: 311, name: "Syncros" },
    { id: 65534, name: "Actigraphcorp" },
];

/**
 * Get manufacturer name by ID
 */
export function getManufacturerName(id: number): string {
    const manufacturer = MANUFACTURERS.find((m) => m.id === id);
    return manufacturer ? manufacturer.name : `Unknown (${id})`;
}

/**
 * Get manufacturer ID by name (case-insensitive)
 */
export function getManufacturerId(name: string): number | undefined {
    const manufacturer = MANUFACTURERS.find(
        (m) => m.name.toLowerCase() === name.toLowerCase()
    );
    return manufacturer?.id;
}
